# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: workflow_dispatch

jobs:
  setup-build-publish-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update build version
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          sed -i 's/SHORT_SHA/'`echo ${GITHUB_SHA} | cut -c1-7`'/g' ./version.json
          sed -i 's/ENV/'"$BUILD_ENV"'/g' ./version.json
